"""Sync skills_demo and mcp_server_demo from Applications/ to assets/enterprise_5days/.

Source of truth lives under Applications/. The enterprise course package gets a
path-adjusted copy plus a warning banner on README files so students running
inside assets/enterprise_5days/ do not need repo-root paths.

Usage:
    python tools/sync_enterprise_assets.py            # write (default)
    python tools/sync_enterprise_assets.py --check    # exit 1 if out of sync
    python tools/sync_enterprise_assets.py --verbose  # show every action
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

WARNING_BANNER = (
    "<!-- AUTO-GENERATED by tools/sync_enterprise_assets.py — do not edit by hand. "
    "Source lives in Applications/. -->\n\n"
)

SKIP_DIR_NAMES = frozenset({"__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"})
SKIP_SUFFIXES = frozenset({".pyc", ".pyo"})


@dataclass(frozen=True)
class SyncPair:
    src: Path
    dst: Path


SYNC_PAIRS: tuple[SyncPair, ...] = (
    SyncPair(
        src=REPO_ROOT / "Applications" / "skills_demo",
        dst=REPO_ROOT / "assets" / "enterprise_5days" / "skills_demo",
    ),
    SyncPair(
        src=REPO_ROOT / "Applications" / "mcp_server_demo",
        dst=REPO_ROOT / "assets" / "enterprise_5days" / "mcp_server_demo",
    ),
    # utils/ is intentionally NOT here — `tools/restore_utils_symlink.py` owns
    # that sync (symlink first, copy fallback with .utils_is_copy marker).
    # data/ is intentionally NOT here — main repo data/ holds training corpora
    # while enterprise_5days/data/ is a curated subset with course-only files
    # (enterprise_docs/, eval_dataset.jsonl). Forward-syncing would delete them.
)


def expected_target_bytes(src_root_name: str, rel_posix: str, raw: bytes) -> bytes:
    """Return the bytes that the target file should contain.

    Only README.md files get transformed:
      - skills_demo/README.md additionally has two repo-root-relative paths swapped
        for course-package-relative paths.
      - all README.md files get the warning banner prepended.
    """
    if not rel_posix.endswith("README.md"):
        return raw
    text = raw.decode("utf-8")
    if src_root_name == "skills_demo" and rel_posix == "README.md":
        text = text.replace("# In repo root", "# In assets/enterprise_5days/")
        text = text.replace("'Applications/skills_demo'", "'skills_demo'")
    return (WARNING_BANNER + text).encode("utf-8")


def iter_source_files(src_root: Path) -> list[Path]:
    """Walk src_root yielding files we should sync (skipping caches and .pyc)."""
    out: list[Path] = []
    for path in src_root.rglob("*"):
        if not path.is_file():
            continue
        if any(part in SKIP_DIR_NAMES for part in path.relative_to(src_root).parts):
            continue
        if path.suffix in SKIP_SUFFIXES:
            continue
        out.append(path)
    return out


def iter_target_files(dst_root: Path) -> list[Path]:
    """Walk dst_root yielding existing files (so we can detect stale copies)."""
    if not dst_root.exists():
        return []
    out: list[Path] = []
    for path in dst_root.rglob("*"):
        if not path.is_file():
            continue
        if any(part in SKIP_DIR_NAMES for part in path.relative_to(dst_root).parts):
            continue
        if path.suffix in SKIP_SUFFIXES:
            continue
        out.append(path)
    return out


@dataclass
class Action:
    kind: str  # "write", "delete", "ok"
    path: Path
    reason: str = ""


def plan_pair(pair: SyncPair) -> list[Action]:
    actions: list[Action] = []
    src_files = iter_source_files(pair.src)
    src_rels = {p.relative_to(pair.src).as_posix() for p in src_files}

    for src_file in src_files:
        rel = src_file.relative_to(pair.src).as_posix()
        target = pair.dst / src_file.relative_to(pair.src)
        expected = expected_target_bytes(pair.src.name, rel, src_file.read_bytes())
        if not target.exists():
            actions.append(Action("write", target, "missing"))
            continue
        if target.read_bytes() != expected:
            actions.append(Action("write", target, "out of date"))
        else:
            actions.append(Action("ok", target))

    # Detect stale files in dst that no longer exist in src.
    for tgt_file in iter_target_files(pair.dst):
        rel = tgt_file.relative_to(pair.dst).as_posix()
        if rel not in src_rels:
            actions.append(Action("delete", tgt_file, "no longer in source"))

    return actions


def apply_action(action: Action, pair: SyncPair) -> None:
    if action.kind == "write":
        rel = action.path.relative_to(pair.dst).as_posix()
        src_file = pair.src / action.path.relative_to(pair.dst)
        expected = expected_target_bytes(pair.src.name, rel, src_file.read_bytes())
        action.path.parent.mkdir(parents=True, exist_ok=True)
        action.path.write_bytes(expected)
    elif action.kind == "delete":
        action.path.unlink()
        # Best-effort prune of empty parent directories up to dst root.
        parent = action.path.parent
        while parent != pair.dst and parent.is_dir() and not any(parent.iterdir()):
            parent.rmdir()
            parent = parent.parent


def fmt_action(action: Action, pair: SyncPair) -> str:
    rel = action.path.relative_to(pair.dst).as_posix()
    return f"  [{action.kind:<6}] {pair.dst.name}/{rel}" + (
        f"  ({action.reason})" if action.reason else ""
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if sync would change anything; do not write.",
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true", help="Print every file action."
    )
    args = parser.parse_args(argv)

    total_changes = 0
    for pair in SYNC_PAIRS:
        if not pair.src.exists():
            print(f"ERROR: source missing: {pair.src}", file=sys.stderr)
            return 2
        actions = plan_pair(pair)
        non_ok = [a for a in actions if a.kind != "ok"]
        total_changes += len(non_ok)

        if args.verbose or non_ok:
            print(f"== {pair.src.name} -> {pair.dst} ==")
        for action in actions:
            if action.kind == "ok" and not args.verbose:
                continue
            print(fmt_action(action, pair))

        if not args.check:
            for action in non_ok:
                apply_action(action, pair)

    if args.check:
        if total_changes:
            print(f"\nCHECK FAILED: {total_changes} file(s) out of sync.")
            return 1
        print("CHECK OK: enterprise_5days assets are in sync.")
        return 0

    print(f"\nDONE: {total_changes} file(s) updated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
